// Mocks generated by Mockito 5.4.4 from annotations
// in nuevo_app/test/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nuevo_app/data/datasources/local/local_data_source.dart'
    as _i10;
import 'package:nuevo_app/data/datasources/remote/api_client.dart' as _i4;
import 'package:nuevo_app/data/models/api_response.dart' as _i2;
import 'package:nuevo_app/data/models/auth_response_model.dart' as _i6;
import 'package:nuevo_app/data/models/diet_plan_model.dart' as _i9;
import 'package:nuevo_app/data/models/lab_request_model.dart' as _i8;
import 'package:nuevo_app/data/models/subscription_model.dart' as _i3;
import 'package:nuevo_app/data/models/user_model.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscriptionModel_1 extends _i1.SmartFake
    implements _i3.SubscriptionModel {
  _FakeSubscriptionModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>> login(
          _i6.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>.value(
            _FakeApiResponse_0<_i6.AuthResponseData>(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>> register(
          _i6.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>.value(
            _FakeApiResponse_0<_i6.AuthResponseData>(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<_i6.AuthResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i5.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> forgotPassword(
          _i6.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #forgotPassword,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> resendResetCode(
          _i6.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendResetCode,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #resendResetCode,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> verifyResetCode(
          _i6.VerifyResetCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #verifyResetCode,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> resetPassword(
          _i6.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i2.ApiResponse<_i7.UserModel>> getUserProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i2.ApiResponse<_i7.UserModel>>.value(
            _FakeApiResponse_0<_i7.UserModel>(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<_i7.UserModel>>);

  @override
  _i5.Future<_i2.ApiResponse<_i7.UserModel>> updateProfile(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i5.Future<_i2.ApiResponse<_i7.UserModel>>.value(
            _FakeApiResponse_0<_i7.UserModel>(
          this,
          Invocation.method(
            #updateProfile,
            [data],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<_i7.UserModel>>);

  @override
  _i5.Future<_i2.ApiResponse<void>> checkEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkEmail,
          [email],
        ),
        returnValue:
            _i5.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #checkEmail,
            [email],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<void>>);

  @override
  _i5.Future<_i3.SubscriptionModel> getSubscriptionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionStatus,
          [],
        ),
        returnValue:
            _i5.Future<_i3.SubscriptionModel>.value(_FakeSubscriptionModel_1(
          this,
          Invocation.method(
            #getSubscriptionStatus,
            [],
          ),
        )),
      ) as _i5.Future<_i3.SubscriptionModel>);

  @override
  _i5.Future<_i3.SubscriptionModel> getSubscriptionDetails() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionDetails,
          [],
        ),
        returnValue:
            _i5.Future<_i3.SubscriptionModel>.value(_FakeSubscriptionModel_1(
          this,
          Invocation.method(
            #getSubscriptionDetails,
            [],
          ),
        )),
      ) as _i5.Future<_i3.SubscriptionModel>);

  @override
  _i5.Future<_i2.ApiResponse<_i8.LabRequestData>> createLabRequest(
          _i8.CreateLabRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLabRequest,
          [request],
        ),
        returnValue: _i5.Future<_i2.ApiResponse<_i8.LabRequestData>>.value(
            _FakeApiResponse_0<_i8.LabRequestData>(
          this,
          Invocation.method(
            #createLabRequest,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<_i8.LabRequestData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i8.LabRequestListResponseData>>
      getLabRequests() => (super.noSuchMethod(
            Invocation.method(
              #getLabRequests,
              [],
            ),
            returnValue: _i5
                .Future<_i2.ApiResponse<_i8.LabRequestListResponseData>>.value(
                _FakeApiResponse_0<_i8.LabRequestListResponseData>(
              this,
              Invocation.method(
                #getLabRequests,
                [],
              ),
            )),
          ) as _i5.Future<_i2.ApiResponse<_i8.LabRequestListResponseData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i8.LabRequestData>> getLabRequestById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLabRequestById,
          [id],
        ),
        returnValue: _i5.Future<_i2.ApiResponse<_i8.LabRequestData>>.value(
            _FakeApiResponse_0<_i8.LabRequestData>(
          this,
          Invocation.method(
            #getLabRequestById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<_i8.LabRequestData>>);

  @override
  _i5.Future<_i2.ApiResponse<_i9.DietPlanModel>> getDietPlan() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDietPlan,
          [],
        ),
        returnValue: _i5.Future<_i2.ApiResponse<_i9.DietPlanModel>>.value(
            _FakeApiResponse_0<_i9.DietPlanModel>(
          this,
          Invocation.method(
            #getDietPlan,
            [],
          ),
        )),
      ) as _i5.Future<_i2.ApiResponse<_i9.DietPlanModel>>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i10.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveAccessToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveAccessToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveRefreshToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> clearSecureData() => (super.noSuchMethod(
        Invocation.method(
          #clearSecureData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isFirstLaunch() => (super.noSuchMethod(
        Invocation.method(
          #isFirstLaunch,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setFirstLaunchComplete() => (super.noSuchMethod(
        Invocation.method(
          #setFirstLaunchComplete,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setThemeMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLastSyncTime(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastSyncTime,
          [time],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearPreferences() => (super.noSuchMethod(
        Invocation.method(
          #clearPreferences,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> handleFirstLaunch() => (super.noSuchMethod(
        Invocation.method(
          #handleFirstLaunch,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
