// Mocks generated by Mockito 5.4.4 from annotations
// in nuevo_app/test/domain/usecases/subscription/get_subscription_status_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nuevo_app/core/errors/failures.dart' as _i5;
import 'package:nuevo_app/domain/entities/subscription.dart' as _i6;
import 'package:nuevo_app/domain/repositories/subscription_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i3.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>
      getSubscriptionStatus() => (super.noSuchMethod(
            Invocation.method(
              #getSubscriptionStatus,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>.value(
                    _FakeEither_0<_i5.Failure, _i6.Subscription>(
              this,
              Invocation.method(
                #getSubscriptionStatus,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>
      getSubscriptionDetails() => (super.noSuchMethod(
            Invocation.method(
              #getSubscriptionDetails,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>.value(
                    _FakeEither_0<_i5.Failure, _i6.Subscription>(
              this,
              Invocation.method(
                #getSubscriptionDetails,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isFeatureUnlocked(
          String? featureName) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFeatureUnlocked,
          [featureName],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isFeatureUnlocked,
            [featureName],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isSubscriptionActive() =>
      (super.noSuchMethod(
        Invocation.method(
          #isSubscriptionActive,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isSubscriptionActive,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
